### ISSUE TITLE
Peer review: Suggestions for Improving Nim Game Algorithm

### ISSUE THREAD

**Issue by marcocolangelo** [lucabubi/Computational-Intelligence#1]
You've written a well organized and commented code, here I'm going to report just a few tips:

1) In the `crossover` function you're dividing by the total fitness to calculate the parents' weights. What happens if the total fitness is zero? This could cause a division by zero error. It might be helpful to add a check for this case

2) As the professor suggested, maybe a `fitness` function only based on winning percentage is not the best option but at least you make your actors play for 1000 games before computing your fitness, this should improve your fitness space variety

3) your code is generally well commented but there are some parts (like the logic behind choosing valid moves in the `adaptive_strategy` function) that could benefit from more detailed comments

**Comment by lucabubi** [comment]
Thanks for the feedback 😀
