### ISSUE TITLE
Lab 2 Peer Review - Simone Giambrone s317002

### ISSUE THREAD

**Issue by JustLooller** [lucabubi/Computational-Intelligence#2]
Hi! After going through your code this is what I noticed:

- First of all, the lab request was to implement an **Evolution Strategy**, such as (1+$\lambda$) or (1,$\lambda$), not an **Evolutionary Algorithm**, but anyway, the code is very well written and full of comments and explanations on what you're doing and how you're doing it, so props for that.
- The implementation of the `mutation()` and `crossover()` functions is really nice, especially weighting the fitness of the parents before crossing over.
- I would've personally increased the number of games per generation and generations, since changes in Evolutionary Algorithms tend to be slow to appear. 

Overall good job on the lab, good luck for the next ones!

**Comment by lucabubi** [comment]
Thanks for the feedback 😀
