### ISSUE TITLE
Lab 9 - Peer Review (lab 3)

### ISSUE THREAD

**Issue by Kalller** [lucabubi/Computational-Intelligence#3]
Hello!

Your code is great! I didn't find anything wrong with it. It was easy to understand and work through. The implementation is quite standard, but that's what makes it strong and efficient in my opinion.

Perhaps the only improvement you could make was in the crossover, which, in my view, is the most crucial part of solving the problem. You could have made it slightly more complex, maybe based on the parents' fitness.

Great job!

**Comment by lucabubi** [comment]
Thanks for the feedback 😀
