### ISSUE TITLE
lab 9 peer review - Paul-Raphael Spazzola Moracchini

### ISSUE THREAD

**Issue by Paul-Raphael** [lucabubi/Computational-Intelligence#4]
Hello,

Here are some little comments and thoughts about your work for lab 9.
Your code follows the basic idea of EA which is a good thing for understandability and to make sure to not go wrong, however it could have been good considering the fact that the objective is to optimise the number of fitness calls to only do the crossovers between parents to create children or a mutation on a parent to create a children and not the two things consecutively which loses the interest of having high fitness parents because the offsprings can become very different.
Also implementing multi cut crossovers could have been a good way to make your code more efficient but overall I loved what you did.

Keep going and good luck for your next lab !

**Comment by lucabubi** [comment]
Thanks for the feedback 😀
