### ISSUE TITLE
Lab 9 peer review - Paolo Magliano s314867

### ISSUE THREAD

**Issue by paolo-magliano** [lucabubi/Computational-Intelligence#5]
The project is well written, the code is clear and well structured, the documentations is really complete and almost perfect, explains all the ideas behind and how they are implemented.

The most relevant problem of this project is the lack of new and original ideas to solve it with different points of view. The main goal it's to try to discover various ways to implement possible solutions but only one idea is developed. Also a simple variation of the crossover, mutation or selection method could be a good starting point to explore better alterative.

**Comment by lucabubi** [comment]
Thanks for the feedback 😀
