### ISSUE TITLE
Lab9 Review Raffaele Viola - s309063

### ISSUE THREAD

**Issue by RaffaeleViola** [lucabubi/Computational-Intelligence#6]
Your code is well written and structured. The readme file is also pretty clear.

Here are some considerations about your work:

- You could create a class Individual or a similar data structure in order to save the fitness computation of the elite/parent individuals and avoid to recompute it at every step
- A better improvements for the fitness calls would be to create an hash map (python dictionary) and store as a key the genome of the individuals generated (you can use a tuple as key because it is natively hash-able) and as value the fitness. In this way you could avoid to recompute the fitness for already seen individuals.
- You could try to use different type of crossover other than the one cut. For instance you could use the uniform crossover that should be useful with a wide genome like the one of this problem. 

Overall good job, the model is standard but effective enough.

**Comment by lucabubi** [comment]
Thanks for the feedback 😀
